apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    checksum/config: 02a671e62a338309f6e6c02e15af807b61e2a3cf567afc0012d5c8183618c4e6
    checksum/credentials: 966531d4d86c92ffefbdb5906542b4bd4c52edba13e0cdcf81c50a7192921d85
    checksum/filecredentials: ec843a184f0c33c106ffab23e1d903db4c526b5120322933b4890decd5ad2d76
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    iam.amazonaws.com/role: arn:aws:iam::338360549315:role/loki-seed-application-role
    meta.helm.sh/release-name: seed
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-06-14T07:32:26Z"
  labels:
    app: bootstrap
    app.kubernetes.io/managed-by: Helm
    chart: capillary-base-jobs-0.1.2
    heritage: Helm
  name: seed-20220614-07-32-26
  namespace: default
  resourceVersion: "5475725"
  selfLink: /apis/batch/v1/namespaces/default/jobs/seed-20220614-07-32-26
  uid: 9c8d81d1-ef03-451c-b1ec-2976e8cf8a48
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 9c8d81d1-ef03-451c-b1ec-2976e8cf8a48
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        iam.amazonaws.com/role: arn:aws:iam::338360549315:role/loki-seed-application-role
      creationTimestamp: null
      labels:
        app: seed
        controller-uid: 9c8d81d1-ef03-451c-b1ec-2976e8cf8a48
        job-name: seed-20220614-07-32-26
        release: seed
    spec:
      containers:
      - env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_REGION
              name: seed-configs
        - name: CLUSTER
          valueFrom:
            secretKeyRef:
              key: CLUSTER
              name: seed-configs
        - name: PGSQL_HOST
          valueFrom:
            secretKeyRef:
              key: PGSQL_HOST
              name: seed-configs
        - name: TZ
          valueFrom:
            secretKeyRef:
              key: TZ
              name: seed-configs
        - name: PGSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PGSQL_PASSWORD
              name: seed-credentials
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              key: PGSQL_USER
              name: seed-credentials
        image: ibbuu/killbill-postgres:1
        imagePullPolicy: IfNotPresent
        name: seed
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/credentialfiles/
          name: seed-file-credentials-vol
        - mountPath: /var/log/dumps
          name: dump-vol
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: seed-file-credentials-vol
        secret:
          defaultMode: 420
          secretName: seed-file-credentials
      - hostPath:
          path: /var/log/dumps/seed
          type: DirectoryOrCreate
        name: dump-vol
status:
  conditions:
  - lastProbeTime: "2022-06-14T07:38:46Z"
    lastTransitionTime: "2022-06-14T07:38:46Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  startTime: "2022-06-14T07:32:27Z"
